version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - gocritic
    - misspell
    - nilerr
    - prealloc
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - "(*database/sql.DB).Close"
        - "(*database/sql.Rows).Close"
        - "(*database/sql.Tx).Rollback"
        - "(*github.com/jmoiron/sqlx.DB).Close"
        - "(*github.com/jmoiron/sqlx.DB).Exec"
        - "(*moonshine/internal/repository.Database).Close"
        - "(*github.com/gorilla/websocket.Conn).Close"
        - "(*github.com/gorilla/websocket.Conn).SetReadDeadline"
        - "(*github.com/gorilla/websocket.Conn).SetWriteDeadline"
        - "(*github.com/redis/go-redis/v9.Client).Close"
        - "(io.Closer).Close"
    govet:
      disable:
        - copylocks
  exclusions:
    rules:
      - linters:
          - errcheck
        path: "_test\\.go"
